version: '3.7'

services:
  codejam_api:
    image: nnguyen2dpe/codejam-api:latest
    container_name: codejam-api
    restart: always
    ports:
      - "8084:5000"
    links:
      - mongo_host
  endorsement_api:
    image: nnguyen2dpe/endorsement-api:latest
    container_name: endorsement-api
    restart: always
    ports:
      - "8083:5000"    
    links:
      - postgresql_host  
  mongo_host:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db
  postgresql_host:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pg-db-data:/var/lib/postgresql/data
volumes:
  mongo-db-data: {}
  pg-db-data: {}